debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/gnsslite
frame_id: gnsslite #TODO: change it in the future
config_on_startup: false
uart1:
  baudrate: 460800
rate: 20
nav_rate: 4
publish:
  all: true